url-setting:
  home-page: https://travel.state.gov/content/travel/en/legal/visa-law0/visa-bulletin.html
  sample-bulletin: https://travel.state.gov/content/travel/en/legal/visa-law0/visa-bulletin/2020/visa-bulletin-for-december-2019.html
  root-url: https://travel.state.gov/content/travel/en/legal/visa-law0/visa-bulletin
visa-bulletin-req-year: 2015
